### ISSUE TITLE
Time of code？

### ISSUE THREAD

**Issue by Johnson-yue** [brownvc/decoupled-style-descriptors#1]
When do you plan to release the code

**Comment by ZQ32** [comment]
When do you plan to release the code??

**Comment by jamestompkin** [comment]
Hi everyone - yes, I'm sorry that it has taken us so long; it's still on the cards but I can't provide a timeline yet.
I'm afraid that the tumultuous year affected this project.

**Comment by jamestompkin** [comment]
Just to say that the dataset is now out; working on the code!

**Comment by vijay1131** [comment]
Great work. Eagerly waiting for the code!

**Comment by TotalChest** [comment]
When do you plan to release the code?

**Comment by lilong-wen** [comment]
I'm still waiting in 2022.

**Comment by sainikhileshreddy** [comment]
This is interesting project and would be really helpful if you can provide resources or code to process the dataset.

Can we know the possible time it might take to release the code or even model? 

Thanks! Good project!

**Comment by jamestompkin** [comment]
This is now all done (a few months back now). Thanks all for the pushes.
