### ISSUE TITLE
custom handwriting?

### ISSUE THREAD

**Issue by SB2020-eye** [brownvc/decoupled-style-descriptors#7]
Is one able to use this to recreate a custom handwriting style (ie, a handwriting style we have images of)?

**Comment by jamestompkin** [comment]
Hi there - sorry for the long delay.

If you have vector data for the handwriting, then it's possible yes. 
Without, i.e., with only a photo, then there's a step missing.
So, I'm afraid it is non-trivial.

Best wishes,
James
